version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        # image: mysql:5.7.16
        dockerfile: deploy/database.docker
        environment:
            - "MYSQL_ROOT_PASSWORD=umvashA@200"
            - "MYSQL_DATABASE=evuzepharmacy"
        ports:
            - "3306:3306"
    cache:
        image: redis:3.0
        ports:
            - "6379:6379"

# version: '2'
# services:
#   data:
#     image: busybox
#     volumes:
#       - /var/lib/mysql
#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: evuze
#       MYSQL_DATABASE: evuze
#       MYSQL_USER: evuze
#       MYSQL_PASSWORD: evuze
#     volumes_from:
#       - data
#     volumes:
#       - ./misc/data:/root/data
#   nginx:
#     build: Dockerfiles/nginx/.
#     ports:
#       - "8080:80"
#     links:
#       - web
#   web:
#     build: Dockerfiles/php-fpm/.
#     volumes:
#       - .:/var/www/html
#     links:
#       - mysql
#     environment:
#       DB_HOST: mysql