version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=evuze
      - MARIADB_USER=evuze
      - MARIADB_DATABASE=evuze
      - MARIADB_PASSWORD=evuze
    volumes:
      - ./my_custom.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=evuze
      - DB_DATABASE=evuze
      - DB_PASSWORD=evuze
    depends_on:
      - mariadb
    ports:
      - 8080:3000
    volumes:
      - ./:/app
